version: "3"
services:
  werk:
    container_name: werk_web
    environment:
      TZ: "America/Chicago"
      ADMIN_NAME: "admin"
      ADMIN_PASS: "changeme"
      HOST_IP: "host_ip_address_here"
    build:
      context: .
    ports:
      - 5554:5554
    volumes: 
      - ./data:/data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5554
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  database:
    container_name: werk_mongodb
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      TZ: "America/Chicago"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  database-web:
    container_name: werk_mongodb_web
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      TZ: "America/Chicago"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_NOTIFICATION_URL=[SomeWebHook]
    restart: unless-stopped
    command: --interval 60