name: Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish server tags as releases.
    tags: [ 'v*.*.*' ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  tests:
    uses: ./.github/workflows/lint-test-app.yml

  # Used https://github.com/blakeblackshear/frigate/blob/dev/.github/workflows/release.yml
  build_and_publish:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: lowercaseRepo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag variables
        run: |
          BRANCH=$([[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "main" || echo "dev")
          echo "BASE=ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}" >> $GITHUB_ENV
          echo "BUILD_TAG=${BRANCH}-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "CLEAN_VERSION=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | sed 's/^[v]//')" >> $GITHUB_ENV
      - name: Tag and push the main image
        run: |
          VERSION_TAG=${BASE}:${CLEAN_VERSION}
          PULL_TAG=${BASE}:${BUILD_TAG}
          docker build . --tag ${VERSION_TAG}
          docker push ${VERSION_TAG}

  release:
    uses: ./.github/workflows/conventional-release.yml
    needs: [build_and_publish]