name: Lint-Test-PR

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    pull_request:
        branches: [ "main" ]

jobs:
    tests:
        uses: ./.github/workflows/lint-test-app.yml